site_name: pytest-freezegun
site_description: Wrap tests with fixtures in freeze_time
site_author: Tomasz Kontusz

theme: readthedocs

repo_url: https://github.com/ktosiek/pytest-freezegun

pages:
- Home: index.md
